### ISSUE TITLE
Add support for mobile rendering of static content

### ISSUE THREAD

**Issue by Gordonei** [dronesar/dronesar-frontend#12]
Currently rendering on my phone looks like this:

![dronesar_on_phone](https://user-images.githubusercontent.com/1272984/55681316-43f06200-5925-11e9-883a-bb23ad46114b.png)

It would be nice to be able to view the static content on a phone (i.e. not the demo). I imagine a lot of the trouble is the portrait vs landscape orientation, as well as some image sizing issues.

**Comment by peterscottsa** [comment]
@Gordonei This is fixed
