### ISSUE TITLE
Update dataset descriptions

### ISSUE THREAD

**Issue by Gordonei** [dronesar/dronesar-frontend#14]
Please provide a description for [`dataset_4`](https://github.com/Gordonei/CloudSAR/blob/master/resources/samples/dataset_4.txt).

Also, please update the descriptions of the datasets to include the times and dates of the flight, using the ISO8601 format (with second resolution and timezones).

**Comment by darrynjordan** [comment]
Descriptions updated for all datasets. Timestamp and dimensions of each image are now included.
